//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaLamViec
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CaLamViec()
        {
            this.ThongKeCongViecTrongNgays = new HashSet<ThongKeCongViecTrongNgay>();
        }
    
        public int Id { get; set; }
        public string NoiDung { get; set; }
        public Nullable<double> TongGioLam { get; set; }
        public Nullable<bool> KhongGioiHanGio { get; set; }
        public Nullable<double> SomToiDa { get; set; }
        public Nullable<double> TreToiDa { get; set; }
        public Nullable<double> HeSo { get; set; }
        public Nullable<double> GioNghi { get; set; }
        public Nullable<bool> TangCaGioVao { get; set; }
        public Nullable<bool> TangCaGioRa { get; set; }
        public Nullable<double> GioTangCaToiDa { get; set; }
        public Nullable<bool> CaDem { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ThongKeCongViecTrongNgay> ThongKeCongViecTrongNgays { get; set; }
    }
}
