//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LenhSanXuat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LenhSanXuat()
        {
            this.ChiTiets = new HashSet<ChiTiet>();
            this.CongViecs = new HashSet<CongViec>();
            this.LenhSanXuats1 = new HashSet<LenhSanXuat>();
        }
    
        public int Id { get; set; }
        public string MaSo { get; set; }
        public string LanTest { get; set; }
        public string NoiDung { get; set; }
        public string YeuCau { get; set; }
        public System.DateTime NgayYCHT { get; set; }
        public System.DateTime NgayNhap { get; set; }
        public bool ThietKe { get; set; }
        public bool GiaCong { get; set; }
        public string GhiChu { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayPKT_Nhan { get; set; }
        public Nullable<System.DateTime> NgayYCHT_TK { get; set; }
        public Nullable<System.DateTime> NgayHTTK_NhanVien { get; set; }
        public Nullable<System.DateTime> NgayXCK_Nhan { get; set; }
        public Nullable<System.DateTime> NgayHTGC_TroLi { get; set; }
        public Nullable<System.DateTime> NgayHT_GiaoHang { get; set; }
        public Nullable<bool> KetQua { get; set; }
        public Nullable<System.DateTime> NgayKetQua { get; set; }
        public Nullable<System.DateTime> NgayHHBH { get; set; }
        public string GhiChu_PKD { get; set; }
        public string GhiChu_PKT { get; set; }
        public string GhiChu_QD { get; set; }
        public string GhiChu_TroLi { get; set; }
        public Nullable<System.DateTime> NgayHTTK { get; set; }
        public Nullable<System.DateTime> NgayHTGC { get; set; }
        public string MaSP { get; set; }
        public Nullable<System.DateTime> NgayCoPhoi { get; set; }
        public Nullable<System.DateTime> NgayBD_BaoPhoi { get; set; }
        public string SoPO { get; set; }
        public Nullable<int> SoBo { get; set; }
        public byte[] RowVersion { get; set; }
        public int LenhSanXuat_KhachHang { get; set; }
        public Nullable<int> LenhSanXuat_LenhSanXuat { get; set; }
        public Nullable<int> LenhSanXuat_NhanVienPKD { get; set; }
        public Nullable<int> LenhSanXuat_NhanVienPKT { get; set; }
        public Nullable<int> LenhSanXuat_NhanVienPKT1 { get; set; }
        public Nullable<int> LenhSanXuat_TroLiSX { get; set; }
        public Nullable<int> LenhSanXuat_TroLiSX1 { get; set; }
        public Nullable<int> LenhSanXuat_NguoiDung { get; set; }
        public Nullable<int> LenhSanXuat_NguoiDung1 { get; set; }
        public Nullable<int> LenhSanXuat_NguoiDung2 { get; set; }
        public Nullable<int> LenhSanXuat_NguoiDung3 { get; set; }
        public Nullable<int> LenhSanXuat_NguoiDung4 { get; set; }
        public Nullable<int> PhanLoaiLSX { get; set; }
        public Nullable<int> PhanLoaiLSX2 { get; set; }
        public string GhiChu_TrPKT { get; set; }
        public Nullable<bool> Huy { get; set; }
        public Nullable<bool> NhapMaSo { get; set; }
        public string MaDuAn { get; set; }
        public Nullable<System.Guid> MaDelay { get; set; }
        public Nullable<System.DateTime> NgayGiaoHang { get; set; }
        public Nullable<bool> PhongKinhDoanh { get; set; }
        public Nullable<bool> LapRap { get; set; }
        public Nullable<System.DateTime> NgayYeuCauCapNhatThongTin { get; set; }
        public Nullable<System.DateTime> NgayXCKDongYCapNhatThongTin { get; set; }
        public Nullable<System.DateTime> NgayYCHT_TKCT { get; set; }
        public Nullable<System.DateTime> NgayHTTKConLai_NhanVien { get; set; }
        public Nullable<int> MucDoUuTienGC { get; set; }
        public Nullable<decimal> DoanhThu { get; set; }
        public Nullable<int> TrangThai { get; set; }
        public Nullable<bool> TreHan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTiet> ChiTiets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LenhSanXuat> LenhSanXuats1 { get; set; }
        public virtual LenhSanXuat LenhSanXuat1 { get; set; }
    }
}
