//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenCong
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenCong()
        {
            this.CongViecs = new HashSet<CongViec>();
        }
    
        public int Id { get; set; }
        public int STT { get; set; }
        public string NoiDung { get; set; }
        public Nullable<System.DateTime> NgayCoPhoi { get; set; }
        public Nullable<int> SL_GiaCong { get; set; }
        public Nullable<System.DateTime> NgayYCHT { get; set; }
        public Nullable<System.DateTime> NgayHTTT { get; set; }
        public Nullable<int> SL_HoanThanh { get; set; }
        public string GhiChu { get; set; }
        public bool DaGCN { get; set; }
        public byte[] RowVersion { get; set; }
        public int NguyenCong_ChiTiet { get; set; }
        public Nullable<int> NguyenCong_LanGiaCong { get; set; }
        public int NguyenCong_ToSX { get; set; }
        public string LanGiaCong2 { get; set; }
        public Nullable<int> MayKH { get; set; }
        public Nullable<int> NhanVienKH { get; set; }
        public string ThoiGianKH { get; set; }
        public Nullable<int> Order { get; set; }
        public Nullable<int> MucDoUuTien { get; set; }
        public Nullable<System.DateTime> NgayDKHT { get; set; }
        public Nullable<System.DateTime> NgayDKCP { get; set; }
        public Nullable<System.DateTime> NgayYCCP { get; set; }
        public Nullable<int> SL_KhongDat { get; set; }
        public Nullable<int> NguyenCong_NhomMay { get; set; }
        public Nullable<int> ToSXKH { get; set; }
        public Nullable<int> NguyenCong_LoaiNguyenCong { get; set; }
        public Nullable<int> ThoiGianKHPhut { get; set; }
        public Nullable<double> ThoiGianKHTS { get; set; }
        public Nullable<System.DateTime> ThoiGianKHBD_NguoiNhap { get; set; }
        public Nullable<System.DateTime> ThoiGianKH_BD { get; set; }
        public Nullable<System.DateTime> ThoiGianKH_KT { get; set; }
        public Nullable<System.DateTime> ThoiGianTT_BD { get; set; }
        public Nullable<double> TongTlg_TT { get; set; }
        public Nullable<double> SoSanhTg_KH_TT { get; set; }
        public Nullable<double> TyLeHoanThanh { get; set; }
        public Nullable<double> TyLeDat { get; set; }
        public Nullable<int> NguoiVanHanhDK { get; set; }
        public Nullable<int> NguoiVanHanhTT { get; set; }
        public Nullable<bool> CanDienCuc { get; set; }
        public Nullable<System.DateTime> NgayCoDienCucDK { get; set; }
        public Nullable<bool> CanDCDB { get; set; }
        public Nullable<System.DateTime> NgayCoDCDBDK { get; set; }
        public Nullable<bool> CanDGDB { get; set; }
        public Nullable<System.DateTime> NgayCoDGDBDK { get; set; }
        public Nullable<bool> CanChuongTrinh { get; set; }
        public Nullable<System.DateTime> NgayCoCTDK { get; set; }
        public Nullable<System.DateTime> NgayTTCoDienCuc { get; set; }
        public Nullable<System.DateTime> NgayTTCoDCDB { get; set; }
        public Nullable<System.DateTime> NgayTTCoDGDB { get; set; }
        public Nullable<System.DateTime> NgayTTCoCT { get; set; }
        public Nullable<System.DateTime> NgayDuDK { get; set; }
        public string ViTriChiTiet { get; set; }
    
        public virtual ChiTiet ChiTiet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
        public virtual May May { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual NhanVien NhanVien1 { get; set; }
        public virtual NhanVien NhanVien2 { get; set; }
        public virtual ToSX ToSX { get; set; }
        public virtual ToSX ToSX1 { get; set; }
    }
}
