//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class NguyenCongHL
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NguyenCongHL()
        {
            this.BuocHLs = new HashSet<BuocHL>();
            this.CongViecs = new HashSet<CongViec>();
        }
    
        public int Id { get; set; }
        public int STT { get; set; }
        public string NoiDung { get; set; }
        public byte[] RowVersion { get; set; }
        public int NguyenCongHL_ChiTietHL { get; set; }
        public string MaCongDoan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BuocHL> BuocHLs { get; set; }
        public virtual ChiTietHL ChiTietHL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CongViec> CongViecs { get; set; }
    }
}
