//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OneDuyKhanhDataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OneDuyKhanh4Entities : DbContext
    {
        public OneDuyKhanh4Entities()
            : base("name=OneDuyKhanh4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BuocHL> BuocHLs { get; set; }
        public virtual DbSet<CaLamViec> CaLamViecs { get; set; }
        public virtual DbSet<ChiTietHL> ChiTietHLs { get; set; }
        public virtual DbSet<ChiTiet> ChiTiets { get; set; }
        public virtual DbSet<CongViec2Set> CongViec2Set { get; set; }
        public virtual DbSet<CongViecPhu> CongViecPhus { get; set; }
        public virtual DbSet<CongViec> CongViecs { get; set; }
        public virtual DbSet<HinhDinhKem> HinhDinhKems { get; set; }
        public virtual DbSet<LenhSanXuat> LenhSanXuats { get; set; }
        public virtual DbSet<May> Mays { get; set; }
        public virtual DbSet<NguyenCongHL> NguyenCongHLs { get; set; }
        public virtual DbSet<NguyenCong> NguyenCongs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<ThongKeCongViecTrongNgay> ThongKeCongViecTrongNgays { get; set; }
        public virtual DbSet<ToSX> ToSXes { get; set; }
        public virtual DbSet<BaoTrangThaiMay> BaoTrangThaiMays { get; set; }
    }
}
